services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: gdash_rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    environment:
      RABBITMQ_DEFAUT_USER: $ {RABBITMQ_USER}
      RABBITQ_DEFAUT_PASS: $ {RABBITMQ_PASS}
    networks:
      - gdash_net
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    container_name: gdash_mongodb
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INTIDB_ROOT_USERNAME: $ {MONGO_USER}
      MONGO_INTIDB_ROOT_PASSWORD: $ {MONGO_PASS}
    volumes:
      - ./mongo_data:/data/db
    networks:
      - gdash_net
    env_file:
      - .env

networks:
  gdash_net:
    driver: bridge
